"""
Audit Cache - Deterministic Caching System
Stores and retrieves completed audit reports to avoid unnecessary recomputation.

The cache is based on:
- Framework (NAAC/NBA)
- Criterion ID
- Institution document content (hashed)

This ensures that identical inputs always return cached results.
"""

import hashlib
import json
import os
from pathlib import Path
from typing import Dict, Any, Optional, List
from datetime import datetime, timedelta


class AuditCache:
    """
    Deterministic audit cache system.
    
    Caches audit results based on framework, criterion, and institution content.
    """
    
    def __init__(self, cache_dir: str = "audit_results", ttl_hours: int = 24):
        """
        Initialize audit cache.
        
        Args:
            cache_dir: Directory to store cached results
            ttl_hours: Time-to-live for cached results in hours (0 = no expiration)
        """
        self.cache_dir = Path(cache_dir)
        self.cache_dir.mkdir(exist_ok=True)
        self.ttl_hours = ttl_hours
    
    def generate_cache_key(
        self,
        framework: str,
        criterion: str,
        institution_index_path: Optional[str] = None
    ) -> str:
        """
        Generate deterministic cache key.
        
        The cache key is based on:
        1. Framework (NAAC/NBA)
        2. Criterion ID (e.g., 3.2.1)
        3. Institution index content hash (if available)
        
        Args:
            framework: Framework name (NAAC/NBA)
            criterion: Criterion ID
            institution_index_path: Path to institution index file
            
        Returns:
            SHA256 hash as cache key
        """
        hasher = hashlib.sha256()
        
        # Add framework and criterion
        hasher.update(framework.encode('utf-8'))
        hasher.update(criterion.encode('utf-8'))
        
        # Add institution content hash if available
        if institution_index_path and os.path.exists(institution_index_path):
            try:
                with open(institution_index_path, 'rb') as f:
                    # Hash the index file content
                    hasher.update(f.read())
            except Exception as e:
                print(f"[CACHE WARNING] Could not hash institution index: {e}")
        else:
            # No institution evidence - use placeholder
            hasher.update(b'no_institution_evidence')
        
        return hasher.hexdigest()
    
    def get_cached_audit(self, cache_key: str) -> Optional[Dict[str, Any]]:
        """
        Retrieve cached audit result if it exists and is not expired.
        
        Args:
            cache_key: Cache key generated by generate_cache_key()
            
        Returns:
            Cached audit report or None if not found/expired
        """
        cache_file = self.cache_dir / f"cache_{cache_key}.json"
        
        if not cache_file.exists():
            return None
        
        try:
            with open(cache_file, 'r', encoding='utf-8') as f:
                cached_data = json.load(f)
            
            # Check TTL if enabled
            if self.ttl_hours > 0:
                cached_timestamp = datetime.fromisoformat(cached_data['cache_metadata']['timestamp'])
                age = datetime.now() - cached_timestamp
                
                if age > timedelta(hours=self.ttl_hours):
                    print(f"[CACHE EXPIRED] Cache entry is {age.total_seconds() / 3600:.1f} hours old (TTL: {self.ttl_hours}h)")
                    return None
            
            print(f"[CACHE HIT] Returning cached audit result")
            print(f"  Cached at: {cached_data['cache_metadata']['timestamp']}")
            print(f"  Framework: {cached_data['cache_metadata']['framework']}")
            print(f"  Criterion: {cached_data['cache_metadata']['criterion']}")
            
            return cached_data['report']
            
        except Exception as e:
            print(f"[CACHE ERROR] Failed to load cached result: {e}")
            return None
    
    def save_audit_cache(
        self,
        cache_key: str,
        report: Dict[str, Any],
        framework: str,
        criterion: str
    ):
        """
        Save audit report to cache.
        
        Args:
            cache_key: Cache key generated by generate_cache_key()
            report: Complete audit report to cache
            framework: Framework name
            criterion: Criterion ID
        """
        cache_file = self.cache_dir / f"cache_{cache_key}.json"
        
        # Build cached data with metadata
        cached_data = {
            'cache_key': cache_key,
            'cache_metadata': {
                'timestamp': datetime.now().isoformat(),
                'framework': framework,
                'criterion': criterion,
                'ttl_hours': self.ttl_hours
            },
            'report': report
        }
        
        try:
            with open(cache_file, 'w', encoding='utf-8') as f:
                json.dump(cached_data, f, indent=2, ensure_ascii=False)
            
            print(f"[CACHE SAVE] Stored audit result")
            print(f"  Cache key: {cache_key[:16]}...")
            print(f"  File: {cache_file.name}")
            
        except Exception as e:
            print(f"[CACHE ERROR] Failed to save cache: {e}")
    
    def cache_exists(self, cache_key: str) -> bool:
        """
        Check if cached result exists (ignoring TTL).
        
        Args:
            cache_key: Cache key to check
            
        Returns:
            True if cache file exists
        """
        cache_file = self.cache_dir / f"cache_{cache_key}.json"
        return cache_file.exists()
    
    def clear_cache(self, older_than_hours: Optional[int] = None):
        """
        Clear cached results.
        
        Args:
            older_than_hours: If specified, only clear cache older than this many hours.
                            If None, clear all cache.
        """
        cleared_count = 0
        
        for cache_file in self.cache_dir.glob("cache_*.json"):
            should_delete = False
            
            if older_than_hours is None:
                should_delete = True
            else:
                try:
                    with open(cache_file, 'r', encoding='utf-8') as f:
                        cached_data = json.load(f)
                    
                    cached_timestamp = datetime.fromisoformat(cached_data['cache_metadata']['timestamp'])
                    age = datetime.now() - cached_timestamp
                    
                    if age > timedelta(hours=older_than_hours):
                        should_delete = True
                        
                except Exception:
                    # If we can't read the file, delete it
                    should_delete = True
            
            if should_delete:
                cache_file.unlink()
                cleared_count += 1
        
        print(f"[CACHE CLEAR] Removed {cleared_count} cached result(s)")
    
    def get_cache_stats(self) -> Dict[str, Any]:
        """
        Get cache statistics.
        
        Returns:
            Dictionary with cache statistics
        """
        cache_files = list(self.cache_dir.glob("cache_*.json"))
        total_size = sum(f.stat().st_size for f in cache_files)
        
        # Count by framework
        framework_counts = {}
        for cache_file in cache_files:
            try:
                with open(cache_file, 'r', encoding='utf-8') as f:
                    cached_data = json.load(f)
                framework = cached_data['cache_metadata']['framework']
                framework_counts[framework] = framework_counts.get(framework, 0) + 1
            except Exception:
                pass
        
        return {
            'total_cached_audits': len(cache_files),
            'total_size_bytes': total_size,
            'total_size_mb': round(total_size / (1024 * 1024), 2),
            'by_framework': framework_counts,
            'cache_directory': str(self.cache_dir)
        }


# Singleton instance for convenience
_default_cache = None


def get_default_cache() -> AuditCache:
    """Get the default audit cache instance."""
    global _default_cache
    if _default_cache is None:
        _default_cache = AuditCache()
    return _default_cache


# Convenience functions using default cache
def generate_cache_key(
    framework: str,
    criterion: str,
    institution_index_path: Optional[str] = None
) -> str:
    """Generate cache key using default cache."""
    return get_default_cache().generate_cache_key(framework, criterion, institution_index_path)


def get_cached_audit(cache_key: str) -> Optional[Dict[str, Any]]:
    """Get cached audit using default cache."""
    return get_default_cache().get_cached_audit(cache_key)


def save_audit_cache(
    cache_key: str,
    report: Dict[str, Any],
    framework: str,
    criterion: str
):
    """Save audit to cache using default cache."""
    get_default_cache().save_audit_cache(cache_key, report, framework, criterion)


def cache_exists(cache_key: str) -> bool:
    """Check if cache exists using default cache."""
    return get_default_cache().cache_exists(cache_key)


def clear_cache(older_than_hours: Optional[int] = None):
    """Clear cache using default cache."""
    get_default_cache().clear_cache(older_than_hours)


def get_cache_stats() -> Dict[str, Any]:
    """Get cache statistics using default cache."""
    return get_default_cache().get_cache_stats()
